name: Go
on:
  push:
    tags–ignore:
      - 'v*.*.*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install gpg
        run: sudo apt-get install gpg

      - name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Test
        run: |
          gpg --import test-key.asc
          go test -v .

      - name: Build
        run: go build -v .
